# Generated by Django 5.1.1 on 2024-10-29 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_alter_doctor_rating'),
        ('hospital', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Appointment_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('Status', models.CharField(max_length=255)),
                ('Date', models.DateField()),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('Hospital_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
