# Generated by Django 5.1.1 on 2024-10-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Disease',
            field=models.CharField(default='Chest Paint', max_length=255),
            preserve_default=False,
        ),
    ]
