# Generated by Django 5.1.1 on 2024-10-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='End_time',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Start_time',
            field=models.CharField(),
        ),
    ]
