# Generated by Django 5.1.1 on 2024-10-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_date_alter_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Token_no',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
