# Generated by Django 5.1.1 on 2024-09-19 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Doctor_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Reg_num', models.BigIntegerField()),
                ('Specialization', models.CharField(max_length=255)),
                ('Rating', models.FloatField()),
                ('Current_HOS', models.CharField(max_length=255)),
                ('Availability', models.BooleanField(default=True)),
                ('ID_photo', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('Hospital_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=100)),
                ('Rating', models.FloatField()),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('Medicine_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Medicine', models.CharField(max_length=255)),
                ('Quantity', models.FloatField()),
                ('Strength', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('Notification_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Patient_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Breakfast_time', models.TimeField()),
                ('Lunch_time', models.TimeField()),
                ('Dinner_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('Prescription_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QUEUEDOCHOS',
            fields=[
                ('Queue_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('Hospital_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.BigIntegerField()),
                ('NIC', models.CharField(max_length=20)),
                ('Device_ID', models.CharField(max_length=255)),
                ('Birthday', models.DateField()),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('Medicine_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.medicine')),
                ('Interval', models.CharField(max_length=255)),
                ('Times_per_day', models.IntegerField()),
                ('Monday', models.BooleanField(default=False)),
                ('Tuesday', models.BooleanField(default=False)),
                ('Wednesday', models.BooleanField(default=False)),
                ('Thursday', models.BooleanField(default=False)),
                ('Friday', models.BooleanField(default=False)),
                ('Saturday', models.BooleanField(default=False)),
                ('Sunday', models.BooleanField(default=False)),
                ('Before_meal', models.BooleanField(default=False)),
                ('Quantity', models.CharField(max_length=255)),
                ('Turn_off_after', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='Prescription_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prescription'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('Report_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Report', models.TextField()),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
                ('Prescription_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('Schedule_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('Frequency', models.CharField(max_length=255)),
                ('Monday', models.BooleanField(default=False)),
                ('Tuesday', models.BooleanField(default=False)),
                ('Wednesday', models.BooleanField(default=False)),
                ('Thursday', models.BooleanField(default=False)),
                ('Friday', models.BooleanField(default=False)),
                ('Saturday', models.BooleanField(default=False)),
                ('Sunday', models.BooleanField(default=False)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('Hospital_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('Session_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Diagnosis', models.CharField(max_length=255)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='Session_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.session'),
        ),
        migrations.AddField(
            model_name='patient',
            name='User_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='NoteUser',
            fields=[
                ('Notification_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='User_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='DocRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Max_count', models.IntegerField()),
                ('Appointments_start_time', models.TimeField()),
                ('Appointments_end_time', models.TimeField()),
                ('Patients_attended', models.IntegerField()),
                ('Current_token_no', models.IntegerField()),
                ('Average_time', models.TimeField()),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('Hospital_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
            ],
            options={
                'unique_together': {('Doctor_ID', 'Hospital_ID')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.TextField()),
                ('Hospital_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
            options={
                'unique_together': {('Hospital_ID', 'Patient_ID')},
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('Queue_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.queuedochos')),
                ('Token_no', models.IntegerField(unique=True)),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
            options={
                'unique_together': {('Queue_ID', 'Patient_ID')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Appointment_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('Status', models.CharField(max_length=255)),
                ('Date', models.DateField()),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('Hospital_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
                ('Session_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.session')),
                ('Token_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.queue', to_field='Token_no')),
            ],
        ),
    ]
