# Generated by Django 5.1.1 on 2024-10-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Role',
        ),
        migrations.AddField(
            model_name='user',
            name='IsRegistered',
            field=models.BooleanField(default=False),
        ),
    ]
