# Generated by Django 5.1.1 on 2024-10-02 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Doctor_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('Other_name', models.CharField(max_length=255)),
                ('Birthday', models.CharField(max_length=255)),
                ('Street_No', models.CharField(max_length=255)),
                ('Street_Name', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Postal_Code', models.CharField(max_length=255)),
                ('NIC', models.CharField(max_length=20)),
                ('Reg_num', models.BigIntegerField()),
                ('Specialization', models.CharField(max_length=255)),
                ('Rating', models.FloatField()),
                ('Current_HOS', models.CharField(max_length=255)),
                ('Availability', models.BooleanField(default=True)),
                ('ID_photo', models.BigIntegerField()),
                ('User_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
