# Generated by Django 5.1.1 on 2024-10-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Rating',
            field=models.FloatField(default=0),
        ),
    ]
