# Generated by Django 5.1.1 on 2024-10-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Current_HOS',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='ID_photo',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Reg_num',
            field=models.CharField(),
        ),
    ]
