# Generated by Django 5.1.1 on 2024-10-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_current_hos_alter_doctor_id_photo_and_more'),
        ('doctor_visit_hospital', '0001_initial'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorvisithospital',
            name='Doctor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='doctorvisithospital',
            name='Hospital_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorvisithospital',
            unique_together={('Hospital_ID', 'Doctor_ID')},
        ),
    ]
